id: A472EC6C4
title: Short Prayer to the Three Great Stūpas of Nepal
type: translation
pechas:
- I8195F17D
- I010BCB9A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:02.879537
  last_modified_at: 2023-01-04 11:49:02.879542
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8195F17D/4ACC: '1564'
  I010BCB9A/6C08: '1564'
